spring:
  datasource:
    url: jdbc:mysql://localhost:3306/salbum?characterEncoding=utf8
    username: root
    password: "000000"
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update    