spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sdriver?characterEncoding=utf8
    username: root
    password: '000000'
    driver-class-name: com.mysql.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait-millis: 10000
      validation-query: SELECT 1
mybatis:
  mapper-locations:
  - classpath*:com.qiuxs.**.mapper/*.xml