spring:
  datasource:
    url: jdbc:mysql://hd137:3306/sdriver?characterEncoding=utf8
    username: root
    password: Qiuxs@116279
    driver-class-name: com.mysql.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait-millis: 10000
      validation-query: SELECT 1
mybatis:
  auto-refresh: true
  mapper-locations: 
    - classpath*:com/qiuxs/**/mapper/*Mapper.xml